services:
  - type: web
    name: hoh-realtime
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: HOH_JWT_SECRET
        sync: false
